# Generated by Django 5.1.1 on 2024-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfiguration',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
