# Generated by Django 5.1.1 on 2024-09-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rentalconfiguration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalconfiguration',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('rented', 'Rented'), ('out_of_service', 'Out of Service'), ('completed', 'Completed')], default='reserved', max_length=20),
        ),
    ]
